# Routing frequency analysis — OLMoE-1B-7B

# Model
model_family: olmoe-1b-7b-instruct
base_model_path: allenai/OLMoE-1B-7B-0924-Instruct
model_path: ${base_model_path}

# Data
data_name: pistol_sample1
forget_edge: ['A_B'] # this should be a list # ['A_B'] ['author_1']
use_different_retain_dataset: false # if true, the retain dataset will be different from the forget dataset, otherwise it will be the same as the forget dataset
different_retain_set_path: dataset/unlearning/factual_data.json # this is the path to the different retain dataset, only used if use_different_retain_dataset is true


# Analysis knobs
max_samples: null  # null = use all; set e.g. 128 to cap both sets

# Output
save_path: run_results/routing/${model_family}/${data_name}
